import { PrismaClient, PropertyType, ServiceCategory, LeadStatus } from '@prisma/client';

const prisma = new PrismaClient();

const mockLeads = [
  {
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@example.com",
    phone: "(312) 555-0100",
    address: "123 Main St",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    propertyType: PropertyType.single_family,
    propertyValue: 550000,
    squareFootage: 2200,
    serviceInterest: ServiceCategory.landscaping,
    leadSource: "website",
    leadScore: 85,
    tier: 1,
    status: LeadStatus.new,
    campaign: "Spring Landscaping 2024",
    contactCount: 0,
    urgencyScore: 85,
    propertyScore: 80,
    financialScore: 90,
    demographicScore: 85,
    marketScore: 80,
    notes: "Interested in full backyard renovation with patio",
  },
  {
    firstName: "Mike",
    lastName: "Thompson",
    email: "mike.t@email.com",
    phone: "(312) 555-0101",
    address: "456 Lake St",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    propertyType: PropertyType.single_family,
    propertyValue: 680000,
    squareFootage: 2800,
    serviceInterest: ServiceCategory.roofing,
    leadSource: "referral",
    leadScore: 92,
    tier: 1,
    status: LeadStatus.contacted,
    campaign: "Roofing — Summer Campaign",
    contactCount: 2,
    urgencyScore: 95,
    propertyScore: 90,
    financialScore: 92,
    demographicScore: 88,
    marketScore: 90,
    notes: "Roof damage from storm, needs urgent replacement",
  },
  {
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "jmartinez@gmail.com",
    phone: "(312) 555-0102",
    address: "789 Division St",
    city: "Chicago",
    state: "IL",
    zip: "60622",
    propertyType: PropertyType.single_family,
    propertyValue: 495000,
    squareFootage: 2000,
    serviceInterest: ServiceCategory.hvac,
    leadSource: "google_ads",
    leadScore: 78,
    tier: 1,
    status: LeadStatus.matched,
    campaign: "HVAC Fall Maintenance",
    contactCount: 3,
    urgencyScore: 75,
    propertyScore: 70,
    financialScore: 85,
    demographicScore: 80,
    marketScore: 75,
    notes: "Replacing old furnace, wants energy-efficient model",
  },
  {
    firstName: "David",
    lastName: "Chen",
    email: "dchen@outlook.com",
    phone: "(312) 555-0103",
    address: "321 State St",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    propertyType: PropertyType.condo,
    propertyValue: 420000,
    squareFootage: 1400,
    serviceInterest: ServiceCategory.plumbing,
    leadSource: "social_media",
    leadScore: 88,
    tier: 1,
    status: LeadStatus.converted,
    campaign: "Emergency Plumbing",
    contactCount: 5,
    urgencyScore: 90,
    propertyScore: 75,
    financialScore: 88,
    demographicScore: 92,
    marketScore: 85,
    notes: "Water heater replacement completed successfully",
  },
  {
    firstName: "Amanda",
    lastName: "Wilson",
    email: "awilson@yahoo.com",
    phone: "(312) 555-0104",
    address: "567 Rush St",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    propertyType: PropertyType.single_family,
    propertyValue: 1200000,
    squareFootage: 4500,
    serviceInterest: ServiceCategory.landscaping,
    leadSource: "referral",
    leadScore: 95,
    tier: 1,
    status: LeadStatus.new,
    campaign: "Spring Landscaping 2024",
    contactCount: 0,
    urgencyScore: 95,
    propertyScore: 98,
    financialScore: 95,
    demographicScore: 90,
    marketScore: 95,
    notes: "Large estate, wants complete landscape redesign",
  },
  {
    firstName: "Robert",
    lastName: "Taylor",
    email: "rtaylor@email.com",
    phone: "(312) 555-0105",
    address: "890 Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    zip: "60647",
    propertyType: PropertyType.single_family,
    propertyValue: 525000,
    squareFootage: 2100,
    serviceInterest: ServiceCategory.roofing,
    leadSource: "website",
    leadScore: 72,
    tier: 1,
    status: LeadStatus.contacted,
    campaign: "Roofing — Summer Campaign",
    contactCount: 1,
    urgencyScore: 70,
    propertyScore: 72,
    financialScore: 75,
    demographicScore: 70,
    marketScore: 72,
    notes: "Interested in metal roofing, requested quote",
  },
  {
    firstName: "Emily",
    lastName: "Brown",
    email: "ebrown@gmail.com",
    phone: "(312) 555-0106",
    address: "234 Armitage Ave",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    propertyType: PropertyType.single_family,
    propertyValue: 480000,
    squareFootage: 1900,
    serviceInterest: ServiceCategory.hvac,
    leadSource: "google_ads",
    leadScore: 65,
    tier: 2,
    status: LeadStatus.new,
    campaign: "HVAC Fall Maintenance",
    contactCount: 0,
    urgencyScore: 65,
    propertyScore: 68,
    financialScore: 62,
    demographicScore: 65,
    marketScore: 63,
    notes: "AC not cooling properly, wants inspection",
  },
  {
    firstName: "James",
    lastName: "Anderson",
    email: "janderson@company.com",
    phone: "(312) 555-0107",
    address: "678 Harper Ave",
    city: "Chicago",
    state: "IL",
    zip: "60615",
    propertyType: PropertyType.single_family,
    propertyValue: 390000,
    squareFootage: 1700,
    serviceInterest: ServiceCategory.landscaping,
    leadSource: "website",
    leadScore: 58,
    tier: 2,
    status: LeadStatus.contacted,
    campaign: "Spring Landscaping 2024",
    contactCount: 1,
    urgencyScore: 55,
    propertyScore: 60,
    financialScore: 58,
    demographicScore: 60,
    marketScore: 57,
    notes: "Basic lawn maintenance and hedge trimming",
  },
  {
    firstName: "Lisa",
    lastName: "Garcia",
    email: "lgarcia@email.com",
    phone: "(312) 555-0108",
    address: "901 18th St",
    city: "Chicago",
    state: "IL",
    zip: "60608",
    propertyType: PropertyType.single_family,
    propertyValue: 510000,
    squareFootage: 2300,
    serviceInterest: ServiceCategory.roofing,
    leadSource: "referral",
    leadScore: 81,
    tier: 1,
    status: LeadStatus.matched,
    campaign: "Roofing — Summer Campaign",
    contactCount: 2,
    urgencyScore: 82,
    propertyScore: 78,
    financialScore: 83,
    demographicScore: 80,
    marketScore: 81,
    notes: "Shingle replacement, provided detailed photos",
  },
  {
    firstName: "Kevin",
    lastName: "White",
    email: "kwhite@outlook.com",
    phone: "(312) 555-0109",
    address: "345 Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60640",
    propertyType: PropertyType.single_family,
    propertyValue: 465000,
    squareFootage: 2000,
    serviceInterest: ServiceCategory.hvac,
    leadSource: "social_media",
    leadScore: 74,
    tier: 1,
    status: LeadStatus.new,
    campaign: "HVAC Fall Maintenance",
    contactCount: 0,
    urgencyScore: 72,
    propertyScore: 70,
    financialScore: 76,
    demographicScore: 75,
    marketScore: 73,
    notes: "Furnace making strange noises, wants replacement quote",
  },
  {
    firstName: "Michelle",
    lastName: "Davis",
    email: "mdavis@yahoo.com",
    phone: "(312) 555-0110",
    address: "789 Monroe St",
    city: "Chicago",
    state: "IL",
    zip: "60661",
    propertyType: PropertyType.condo,
    propertyValue: 385000,
    squareFootage: 1300,
    serviceInterest: ServiceCategory.plumbing,
    leadSource: "website",
    leadScore: 91,
    tier: 1,
    status: LeadStatus.converted,
    campaign: "Emergency Plumbing",
    contactCount: 4,
    urgencyScore: 92,
    propertyScore: 80,
    financialScore: 90,
    demographicScore: 95,
    marketScore: 88,
    notes: "Kitchen remodel plumbing completed",
  },
  {
    firstName: "Chris",
    lastName: "Johnson",
    email: "cjohnson@email.com",
    phone: "(312) 555-0111",
    address: "456 Wells St",
    city: "Chicago",
    state: "IL",
    zip: "60610",
    propertyType: PropertyType.single_family,
    propertyValue: 535000,
    squareFootage: 2400,
    serviceInterest: ServiceCategory.landscaping,
    leadSource: "google_ads",
    leadScore: 67,
    tier: 2,
    status: LeadStatus.contacted,
    campaign: "Spring Landscaping 2024",
    contactCount: 1,
    urgencyScore: 65,
    propertyScore: 70,
    financialScore: 68,
    demographicScore: 67,
    marketScore: 66,
    notes: "Front yard landscaping with new plants",
  },
  {
    firstName: "Patricia",
    lastName: "Moore",
    email: "pmoore@gmail.com",
    phone: "(312) 555-0112",
    address: "123 Broadway Ave",
    city: "Chicago",
    state: "IL",
    zip: "60660",
    propertyType: PropertyType.single_family,
    propertyValue: 425000,
    squareFootage: 1800,
    serviceInterest: ServiceCategory.roofing,
    leadSource: "referral",
    leadScore: 45,
    tier: 3,
    status: LeadStatus.new,
    campaign: "Roofing — Summer Campaign",
    contactCount: 0,
    urgencyScore: 40,
    propertyScore: 45,
    financialScore: 48,
    demographicScore: 45,
    marketScore: 42,
    notes: "Minor roof repairs, some leaking in attic",
  },
  {
    firstName: "Daniel",
    lastName: "Lee",
    email: "dlee@company.com",
    phone: "(312) 555-0113",
    address: "567 Belmont Ave",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    propertyType: PropertyType.single_family,
    propertyValue: 575000,
    squareFootage: 2500,
    serviceInterest: ServiceCategory.hvac,
    leadSource: "website",
    leadScore: 83,
    tier: 1,
    status: LeadStatus.matched,
    campaign: "HVAC Fall Maintenance",
    contactCount: 2,
    urgencyScore: 85,
    propertyScore: 82,
    financialScore: 80,
    demographicScore: 83,
    marketScore: 84,
    notes: "Central AC installation for new addition",
  },
  {
    firstName: "Karen",
    lastName: "Martinez",
    email: "kmartinez@outlook.com",
    phone: "(312) 555-0114",
    address: "890 Wilson Ave",
    city: "Chicago",
    state: "IL",
    zip: "60640",
    propertyType: PropertyType.single_family,
    propertyValue: 490000,
    squareFootage: 2100,
    serviceInterest: ServiceCategory.plumbing,
    leadSource: "social_media",
    leadScore: 76,
    tier: 1,
    status: LeadStatus.contacted,
    campaign: "Emergency Plumbing",
    contactCount: 1,
    urgencyScore: 75,
    propertyScore: 72,
    financialScore: 78,
    demographicScore: 77,
    marketScore: 76,
    notes: "Bathroom renovation plumbing work needed",
  },
];

async function main() {
  console.log('🌱 Seeding leads...');

  for (const lead of mockLeads) {
    await prisma.lead.create({
      data: lead,
    });
  }

  console.log('✅ Leads seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding leads:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });