import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const fakeProviders = [
  {
    businessName: "Green Thumb Landscaping",
    ownerName: "Mike Johnson",
    email: "mike@greenthumb.com",
    phone: "(312) 555-0101",
    serviceTypes: ["landscaping"],
    serviceAreas: ["Chicago", "Evanston", "Oak Park"],
    yearsInBusiness: 12,
    status: "active",
    leadCapacity: 25,
    currentLeadCount: 18,
    rating: 4.8,
    totalLeadsSent: 450,
    leadsAccepted: 380,
    leadsConverted: 290,
    totalRevenue: 145000,
    commissionRate: 0.15,
    averageJobValue: 500,
  },
  {
    businessName: "Windy City Roofing Co",
    ownerName: "Sarah Martinez",
    email: "sarah@windycityroofing.com",
    phone: "(773) 555-0202",
    serviceTypes: ["roofing"],
    serviceAreas: ["Chicago", "Naperville", "Aurora"],
    yearsInBusiness: 15,
    status: "active",
    leadCapacity: 20,
    currentLeadCount: 15,
    rating: 4.9,
    totalLeadsSent: 320,
    leadsAccepted: 280,
    leadsConverted: 245,
    totalRevenue: 980000,
    commissionRate: 0.20,
    averageJobValue: 4000,
  },
  {
    businessName: "Chicago HVAC Pros",
    ownerName: "David Chen",
    email: "david@chicagohvac.com",
    phone: "(312) 555-0303",
    serviceTypes: ["hvac"],
    serviceAreas: ["Chicago", "Schaumburg", "Joliet"],
    yearsInBusiness: 18,
    status: "active",
    leadCapacity: 35,
    currentLeadCount: 28,
    rating: 4.7,
    totalLeadsSent: 680,
    leadsAccepted: 600,
    leadsConverted: 520,
    totalRevenue: 780000,
    commissionRate: 0.18,
    averageJobValue: 1500,
  },
  {
    businessName: "Perfect Lawn Services",
    ownerName: "James Wilson",
    email: "james@perfectlawn.com",
    phone: "(773) 555-0404",
    serviceTypes: ["landscaping"],
    serviceAreas: ["Chicago", "Oak Park"],
    yearsInBusiness: 6,
    status: "paused",
    leadCapacity: 15,
    currentLeadCount: 8,
    rating: 4.3,
    totalLeadsSent: 180,
    leadsAccepted: 130,
    leadsConverted: 95,
    totalRevenue: 47500,
    commissionRate: 0.15,
    averageJobValue: 500,
  },
  {
    businessName: "Top Tier Roofing",
    ownerName: "Emily Rodriguez",
    email: "emily@toptierroofing.com",
    phone: "(312) 555-0505",
    serviceTypes: ["roofing"],
    serviceAreas: ["Chicago", "Evanston", "Naperville", "Aurora"],
    yearsInBusiness: 22,
    status: "active",
    leadCapacity: 30,
    currentLeadCount: 25,
    rating: 5.0,
    totalLeadsSent: 890,
    leadsAccepted: 800,
    leadsConverted: 720,
    totalRevenue: 2880000,
    commissionRate: 0.22,
    averageJobValue: 4000,
  },
  {
    businessName: "Precision Plumbing Chicago",
    ownerName: "Robert Taylor",
    email: "rob@precisionplumbing.com",
    phone: "(773) 555-0606",
    serviceTypes: ["plumbing"],
    serviceAreas: ["Chicago", "Schaumburg", "Evanston"],
    yearsInBusiness: 14,
    status: "active",
    leadCapacity: 28,
    currentLeadCount: 21,
    rating: 4.6,
    totalLeadsSent: 420,
    leadsAccepted: 360,
    leadsConverted: 310,
    totalRevenue: 310000,
    commissionRate: 0.17,
    averageJobValue: 1000,
  },
  {
    businessName: "Elite Electrical Services",
    ownerName: "Jennifer Lee",
    email: "jen@eliteelectrical.com",
    phone: "(312) 555-0707",
    serviceTypes: ["electrical"],
    serviceAreas: ["Chicago", "Joliet"],
    yearsInBusiness: 10,
    status: "active",
    leadCapacity: 22,
    currentLeadCount: 16,
    rating: 4.8,
    totalLeadsSent: 540,
    leadsAccepted: 480,
    leadsConverted: 420,
    totalRevenue: 560000,
    commissionRate: 0.16,
    averageJobValue: 1333,
  },
  {
    businessName: "Premier Home Remodeling",
    ownerName: "Michael Brown",
    email: "michael@premierhome.com",
    phone: "(773) 555-0808",
    serviceTypes: ["remodeling", "flooring", "painting"],
    serviceAreas: ["Chicago", "Naperville", "Oak Park"],
    yearsInBusiness: 16,
    status: "active",
    leadCapacity: 18,
    currentLeadCount: 14,
    rating: 4.9,
    totalLeadsSent: 380,
    leadsAccepted: 340,
    leadsConverted: 295,
    totalRevenue: 1450000,
    commissionRate: 0.19,
    averageJobValue: 4915,
  },
  {
    businessName: "Modern Flooring Solutions",
    ownerName: "Amanda Garcia",
    email: "amanda@modernflooring.com",
    phone: "(312) 555-0909",
    serviceTypes: ["flooring"],
    serviceAreas: ["Chicago", "Aurora"],
    yearsInBusiness: 8,
    status: "active",
    leadCapacity: 20,
    currentLeadCount: 12,
    rating: 4.5,
    totalLeadsSent: 290,
    leadsAccepted: 240,
    leadsConverted: 210,
    totalRevenue: 385000,
    commissionRate: 0.15,
    averageJobValue: 1833,
  },
  {
    businessName: "Reliable Painting Pros",
    ownerName: "Christopher White",
    email: "chris@reliablepainting.com",
    phone: "(773) 555-1010",
    serviceTypes: ["painting"],
    serviceAreas: ["Chicago", "Schaumburg", "Evanston"],
    yearsInBusiness: 11,
    status: "active",
    leadCapacity: 24,
    currentLeadCount: 18,
    rating: 4.6,
    totalLeadsSent: 610,
    leadsAccepted: 520,
    leadsConverted: 455,
    totalRevenue: 275000,
    commissionRate: 0.14,
    averageJobValue: 604,
  },
  {
    businessName: "Superior Fence Company",
    ownerName: "Daniel Martinez",
    email: "dan@superiorfence.com",
    phone: "(312) 555-1111",
    serviceTypes: ["fencing"],
    serviceAreas: ["Chicago", "Joliet", "Aurora"],
    yearsInBusiness: 9,
    status: "active",
    leadCapacity: 16,
    currentLeadCount: 10,
    rating: 4.4,
    totalLeadsSent: 270,
    leadsAccepted: 210,
    leadsConverted: 175,
    totalRevenue: 195000,
    commissionRate: 0.15,
    averageJobValue: 1114,
  },
  {
    businessName: "QuickFix Plumbing",
    ownerName: "Lisa Anderson",
    email: "lisa@quickfixplumbing.com",
    phone: "(773) 555-1212",
    serviceTypes: ["plumbing"],
    serviceAreas: ["Chicago", "Oak Park"],
    yearsInBusiness: 7,
    status: "active",
    leadCapacity: 30,
    currentLeadCount: 23,
    rating: 4.7,
    totalLeadsSent: 520,
    leadsAccepted: 460,
    leadsConverted: 390,
    totalRevenue: 420000,
    commissionRate: 0.16,
    averageJobValue: 1077,
  },
  {
    businessName: "All Season HVAC",
    ownerName: "Kevin Thompson",
    email: "kevin@allseasonhvac.com",
    phone: "(312) 555-1313",
    serviceTypes: ["hvac"],
    serviceAreas: ["Chicago", "Naperville", "Schaumburg"],
    yearsInBusiness: 13,
    status: "active",
    leadCapacity: 32,
    currentLeadCount: 26,
    rating: 4.8,
    totalLeadsSent: 740,
    leadsAccepted: 650,
    leadsConverted: 580,
    totalRevenue: 895000,
    commissionRate: 0.17,
    averageJobValue: 1543,
  },
  {
    businessName: "Classic Remodeling Group",
    ownerName: "Patricia Davis",
    email: "patricia@classicremodeling.com",
    phone: "(773) 555-1414",
    serviceTypes: ["remodeling"],
    serviceAreas: ["Chicago", "Evanston", "Aurora"],
    yearsInBusiness: 19,
    status: "active",
    leadCapacity: 15,
    currentLeadCount: 12,
    rating: 4.9,
    totalLeadsSent: 310,
    leadsAccepted: 280,
    leadsConverted: 250,
    totalRevenue: 1680000,
    commissionRate: 0.20,
    averageJobValue: 6720,
  },
  {
    businessName: "Bright Light Electrical",
    ownerName: "Steven Wilson",
    email: "steven@brightlight.com",
    phone: "(312) 555-1515",
    serviceTypes: ["electrical"],
    serviceAreas: ["Chicago", "Joliet", "Naperville"],
    yearsInBusiness: 12,
    status: "active",
    leadCapacity: 25,
    currentLeadCount: 19,
    rating: 4.7,
    totalLeadsSent: 580,
    leadsAccepted: 510,
    leadsConverted: 445,
    totalRevenue: 625000,
    commissionRate: 0.16,
    averageJobValue: 1404,
  },
  {
    businessName: "Garden Paradise Landscaping",
    ownerName: "Michelle Harris",
    email: "michelle@gardenparadise.com",
    phone: "(773) 555-1616",
    serviceTypes: ["landscaping"],
    serviceAreas: ["Chicago", "Oak Park", "Evanston"],
    yearsInBusiness: 5,
    status: "active",
    leadCapacity: 18,
    currentLeadCount: 11,
    rating: 4.2,
    totalLeadsSent: 220,
    leadsAccepted: 170,
    leadsConverted: 135,
    totalRevenue: 92000,
    commissionRate: 0.15,
    averageJobValue: 681,
  },
  {
    businessName: "Ultimate Roofing Solutions",
    ownerName: "Brian Clark",
    email: "brian@ultimateroofing.com",
    phone: "(312) 555-1717",
    serviceTypes: ["roofing"],
    serviceAreas: ["Chicago", "Schaumburg", "Aurora"],
    yearsInBusiness: 20,
    status: "active",
    leadCapacity: 22,
    currentLeadCount: 18,
    rating: 4.8,
    totalLeadsSent: 650,
    leadsAccepted: 580,
    leadsConverted: 510,
    totalRevenue: 2150000,
    commissionRate: 0.21,
    averageJobValue: 4216,
  },
  {
    businessName: "ProPaint Chicago",
    ownerName: "Jessica Moore",
    email: "jessica@propaintchicago.com",
    phone: "(773) 555-1818",
    serviceTypes: ["painting"],
    serviceAreas: ["Chicago", "Naperville"],
    yearsInBusiness: 8,
    status: "active",
    leadCapacity: 20,
    currentLeadCount: 14,
    rating: 4.5,
    totalLeadsSent: 440,
    leadsAccepted: 370,
    leadsConverted: 315,
    totalRevenue: 198000,
    commissionRate: 0.14,
    averageJobValue: 629,
  },
  {
    businessName: "Dependable HVAC Services",
    ownerName: "Thomas Jackson",
    email: "thomas@dependablehvac.com",
    phone: "(312) 555-1919",
    serviceTypes: ["hvac"],
    serviceAreas: ["Chicago", "Joliet", "Evanston"],
    yearsInBusiness: 14,
    status: "active",
    leadCapacity: 28,
    currentLeadCount: 22,
    rating: 4.6,
    totalLeadsSent: 690,
    leadsAccepted: 610,
    leadsConverted: 535,
    totalRevenue: 745000,
    commissionRate: 0.17,
    averageJobValue: 1393,
  },
  {
    businessName: "Master Flooring Experts",
    ownerName: "Nancy Young",
    email: "nancy@masterflooring.com",
    phone: "(773) 555-2020",
    serviceTypes: ["flooring"],
    serviceAreas: ["Chicago", "Oak Park", "Schaumburg"],
    yearsInBusiness: 11,
    status: "active",
    leadCapacity: 19,
    currentLeadCount: 15,
    rating: 4.7,
    totalLeadsSent: 380,
    leadsAccepted: 330,
    leadsConverted: 285,
    totalRevenue: 485000,
    commissionRate: 0.15,
    averageJobValue: 1702,
  },
];

async function seedProviders() {
  console.log('🌱 Seeding providers...');
  
  for (const provider of fakeProviders) {
    try {
      await prisma.provider.create({
        data: provider,
      });
      console.log(`✅ Created: ${provider.businessName}`);
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`⚠️  Skipped (already exists): ${provider.businessName}`);
      } else {
        console.error(`❌ Error creating ${provider.businessName}:`, error.message);
      }
    }
  }
  
  console.log('🎉 Seeding complete!');
}

seedProviders()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });